     
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addressbookdeployment
spec: 
  replicas: 3
  template: 
    metadata:
      labels: 
        app: addressbook
    spec: 
      containers: 
      - name: addressbook-conatiner
        image: chandrapurnimabhatnagar/addressbook:29
        ports:
        - containerPort: 8080
        
        
        
